name: Docker Image Test - quick

on:
  push:
    branches: [ master, dev* ]
  pull_request:
    branches: [ master, dev* ]

jobs:

  build:

    runs-on:  windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        ./build.cmd
    - name: Info on Docker images
      run: |
        docker -v
        docker images
    - name: Run the Docker image
      run: |
        ./run.cmd
    - name: Info on generated files
      run: |
        ls -alt
        ls -alt output
        ls -alt output/*
